# Generated by Django 3.1.1 on 2020-10-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=200)),
                ('numeroCiclos', models.IntegerField(default=5)),
                ('numeroCrditos', models.IntegerField(default=120)),
                ('codigoCarrera', models.CharField(max_length=10)),
                ('numeroDocentes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Paraleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicko', models.IntegerField(default=5)),
                ('nombre', models.CharField(max_length=10)),
                ('numeroEstudiantes', models.IntegerField(default=5)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaapp.carrera')),
            ],
        ),
    ]
