# Generated by Django 3.1.1 on 2020-10-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicko', models.IntegerField(default=5)),
                ('nombre', models.CharField(default='N/A', max_length=10)),
                ('numeroEstudiantes', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera',
            name='codigoCarrera',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombreCarrera',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='numeroDocentes',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.DeleteModel(
            name='Paraleo',
        ),
        migrations.AddField(
            model_name='paralelo',
            name='carrera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pruebaapp.carrera'),
        ),
    ]
