# Generated by Django 3.1.1 on 2020-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapp', '0002_auto_20201002_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='numeroCrditos',
        ),
        migrations.RemoveField(
            model_name='paralelo',
            name='cicko',
        ),
        migrations.AddField(
            model_name='carrera',
            name='numeroCreditos',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='ciclo',
            field=models.IntegerField(default=5),
        ),
    ]
